### PR TITLE
ensure commas in constituency name doesn’t break

### LINKED ISSUE #66: Can't import constituency boundaries with a comma (,) in their name
If you have the uk_constituency_provider_2024 plugin, you cannot import the constituency boundary for any constitueny boundary which has a comma in the name. 

eg " Berwickshire, Roxburgh and Selkirk " 

image

The error message reads "Berwickshire does not seem to be a valid choice."

I think its fair to guess this is because the field takes comma separated values.

### PR DESCRIPTION
**Pull request by dedavidson**

### CODE REVIEW

**Comment by dedavidson** [comment]
@msayoung @Adnan-cds @finnlewis Would somebody be able to review this?

**Comment by Adnan-cds** [comment]
Trying to understand the implication of this change if I type multiple constituency names in the autocomplete lookup textbox.  Like this:
image

Are all the comma separated inputs going to be treated as separate constituencies (as is the case now) or one constituency name with comma in it?

**Comment by dedavidson** [comment]
It will separate them as now. The change wraps constituency names retrieved that have a comma in them with quotes so that they are treated as one.--Sent while I was out and about.On 14 Jun 2024, at 18:18, Adnan ***@***.***> wrote:﻿
Trying to understand the implication of this change if I type multiple constituency names in the autocomplete lookup textbox.  Like this:
image.png (view on web)
Are all the comma separated inputs going to be treated as separate constituencies (as is the case now) or one constituency name with comma in it?

**Review by msayoung — APPROVED** [review]
tested, works fine from an editor point of view.

**Pull request merged**
