### PR TITLE
Add subpathauto module

### LINKED ISSUE #29: Automate URL alias for subpages
At the moment, election subpages are accessed from URLs like /node/1234/results, /node/1234/candidates, /node/1234/electoral-map, /node/1234/share, etc. from the [Elections menu block](https://www.cumberland.gov.uk/election/cumberland-council-election-5-may-2022).  We can manually add URL aliases to improve this. But it would be better to automate this.

Raising this at Will's suggestion.  Copying @willguv @finnlewis @dedavidson @chriswales95

### PR DESCRIPTION
**Pull request by dedavidson**

### CODE REVIEW

**Comment by Adnan-cds** [comment]
Ah.. sorry, I should have mentioned that I tried the subpathauto module already.  It automates the URL alias creation okay, but we can't then use those URL aliases as path conditions in blocks and other places :(  On the other hand, manually added URL aliases work just fine for such purposes.

**Comment by dedavidson** [comment]
Ah ok. Ok the other approach is to manually create/delete the aliases when saving/deleting the election nodes using hooks.

**Comment by Adnan-cds** [comment]
Yeah, it may have to be that way.   This approach wouldn't deal with URL alias changes for the summary page.  But can't think of anything better :(

**Comment by markconroy** [comment]
Can this PR be closed? Looks like we are not going to use subpathauto now, is that correct?

**Comment by finnlewis** [comment]
Converted this to draft for now. Shall close it @dedavidson ?

**Comment by dedavidson** [comment]
Agree close.

**Pull request closed without merging**
