### PR TITLE
Use CDN for highcharts

### LINKED ISSUE #5: Maybe use composer merge plugin
Thanks for all the work on this! Keen to take it for a spin soon.

In the mean time, I was just reading the README.md and note the need for additional external libraries: https://github.com/localgovdrupal/localgov_elections_reporting?tab=readme-ov-file#before-installing

Webform deals with this with the composer merge plugin, see: 

https://www.drupal.org/docs/8/modules/webform/webform-frequently-asked-questions/how-to-use-composer-to-install-libraries-for-the-webform-module

Might we want to do the same, and define a composer.libraries.json in this module for easier inclusion?

### LINKED ISSUE #25: Remove dependencies on Highcharts and use CDN instead
We discovered that it's likely not possible to use the composer-merge plugin (linked issue: #5) to remove the issues we have with the external highcharts dependencies.

Another solution is to use the drupal/charts CDN functionality instead. Users can then change that option if they want later on and require the libraries themselves if they want.

### PR DESCRIPTION
**Pull request by chriswales95**
Closes #25 and #5

### CODE REVIEW

**Comment by chriswales95** [comment]
Hmm conflicts... Let me fix this

**Comment by chriswales95** [comment]
@dedavidson Okay I think I fixed my conflicts. Awaiting your review.

**Review by dedavidson — CHANGES_REQUESTED** [review]
I think we should provide a `composer.libraries.json` like webforms  so people can use that to have the libraries locally if they wish. This would follow the guidance from Charts module 

> If checked, the module will use a CDN unless a local copy of the library is present. If unchecked, all warnings about missing libraries will be disabled.
>
> Relying on a CDN (content delivery network) for external libraries can cause unexpected issues with Ajax and BigPipe support. For more information see: [Issue #1988968](https://www.drupal.org/project/drupal/issues/1988968)

Otherwise tested locally, including update hook, and all fine.

**Comment by ekes** [comment]
> so people can use that to have the libraries locally if they wish

I know for sure that some councils do want to make sure they control where they are serving their assets from.

**Comment by chriswales95** [comment]
@dedavidson I checked the Charts documentation yesterday (seemingly the same thing you read). I think we just add some pointers to their docs which mention the composer merge plugin and their own version of composer.libraries.json.

They mention it here: https://www.drupal.org/docs/contributed-modules/charts/50x-getting-started#s-using-composer-and-wikimediacomposer-merge-plugin

I'm not sure if it's useful for us to duplicate the extra JSON and docs. Just say, if you want to serve the highcharts assets locally follow these steps.

**Comment by chriswales95** [comment]
@ekes Ideally we'd serve locally by default but we can't automatically add in the extra repositories needed and we have our hands tied slightly due to the Charts module's implementation. We tried the composer merge plugin but it doesn't seem to work for this use case.

I know opinions are definitely divided on CDN usage (as are mine's) but it also helps with smoothing out the module's install process (e.g. you don't need to add in the extra repositories) and it will make testing easier with the localgov shared workflow stuff). 

So pros and cons. But, at least there is a path for people to serve locally if they want to. We'll make sure it's highlighted pretty clearly that we recommend not using the CDN.

**Review by dedavidson — APPROVED** [review]

**Comment by Adnan-cds** [comment]
Posting it here for future reference.  We already use [Asset packagist](https://asset-packagist.org/).  So I thought I would just stick to it for Highcharts. After doing `composer require npm-asset/highcharts`, I had to add the following custom code to serve all Highcharts files from the Drupal site:
```
/**
 * Implements hook_library_info_alter().
 */
function custommodule_library_info_alter(&$libraries, $extension) {

  if ($extension === 'charts_highcharts') {
    $is_sourcing_highcharts_from_cdn = Drupal::config('charts.settings')->get('advanced.requirements.cdn');
    if (!$is_sourcing_highcharts_from_cdn) {
      array_walk($libraries, '_custommodule_adjust_highcharts_js_paths');
    }
  }
}

/**
 * Adjusts highcharts file paths in a library.
 *
 * Adjusts script file paths to source everything from the
 * `npm-asset/highcharts` package which is inside the `libraries/highcharts/`
 * directory.
 *
 * The charts_highcharts module expects the following scripts to live in
 * *separate* directories under `libraries/`: highcharts-more.js,
 * highcharts-3d.js, and accessibility.js.  Here we adjust their paths so that
 * these are sourced only from the `libraries/highcharts/` directory.
 *
 * @see charts/modules/charts_highcharts/charts_highcharts.libraries.yml
 */
function _custommodule_adjust_highcharts_js_paths(array &$library): void {

  if (empty($library['js']) || empty($library['cdn'])) {
    return;
  }

  $adjusted_script_paths = [];
  foreach ($library['js'] as $expected_script_path => $attr) {
    $cdn_url = $library['cdn'][$expected_script_path] ?? '';

    $matches = [];
    if (preg_match('#^https://code.highcharts.com/[0-9.]+/(?<path>.*)$#', $cdn_url, $matches)) {
      $script_path_within_highcharts_src = $matches['path'];
      $actual_script_path = '/libraries/highcharts/' . $script_path_within_highcharts_src;
      $adjusted_script_paths[$actual_script_path] = $attr;
    }
    else {
      $adjusted_script_paths[$expected_script_path] = $attr;
    }
  }

  $library['js'] = $adjusted_script_paths;
}
```

**Comment by dedavidson** [comment]
Thanks @Adnan-cds. Just checking you saw the docs section:
> Libraries
>The libraries required by Charts/Highcharts are included, by default via CDN. If you wish to have these locally follow the instructions at https://www.drupal.org/docs/contributed-modules/charts/50x-getting-started#s-using-composer-and-wikimediacomposer-merge-plugin which uses the composer.json provided by the Charts module to install.

**Comment by Adnan-cds** [comment]
Yeah, I am aware of the [repositories snippet](https://git.drupalcode.org/project/charts/-/blob/5.0.x/modules/charts_highcharts/README.md?ref_type=heads) mentioned in charts_highcharts submodule's README (item number **3**).  I just didn't want to bloat our composer.json with it given its considerable length.  So went with npm-asset/highcharts instead which already has all the necessary files.

**Pull request merged**
