### PR TITLE
swaps highcharts for chartjs

### LINKED ISSUE #17: Elections: Swap out Highcharts for Chartjs
Elections uses Highcharts which is proprietary. @markconroy mentioned that we could use Charts.js instead and will try to implement this

Mark, it would be good to make this modular if not much extra work so councils can pick their own chart solution if they wish

### LINKED ISSUE #56: Elections: Swap out Highcharts for other solutions

### PR DESCRIPTION
**Pull request by markconroy**
Closes localgovdrupal/localgov_elections#17 

charts.js is available out of the box as a module for the Drupal Chart module. This PR swaps our use of Highcharts for Chart.js. I haven't tested how the colours and things work as I don't have election data to use.

@chriswales95 can you test this please?

===
Thanks to [Big Blue Door](https://www.bigbluedoor.net/) for sponsoring my time to work on this.

### CODE REVIEW

**Comment by dedavidson** [comment]
@markconroy couple of issues with this. The colour of the bars in the chart has disappeared and so has the majority line. I think this is mostly down in JS in `js/charts-override.js` and `js/election-party-colours.js` and the `hook_chart_alter` on line 456 of the module.

**Comment by markconroy** [comment]
Thanks @dedavidson 

I noticed those files, but I have no content for elections and not even too sure what to add to see things. 

If those items you reported are small fixes, can you apply them? If not, I'll get some content added and have another go at it.

**Comment by dedavidson** [comment]
I've got the bar colours working - I will take a look at the other bits tomorrow.

**Comment by dedavidson** [comment]
image

so chart.js doesn't support some of the features we used in Highcharts:

1. HTML labels - Adding party colour key to the label. We could have a legend box elsewhere
2. Data labels - There is a chart.js [plugin](https://chartjs-plugin-datalabels.netlify.app/) for this which would need added
3. Plot line - There is no way to achieve this without losing the axis labels which might not be an issue and just having one axis line.

Thoughts? @willguv

**Comment by willguv** [comment]
Hi Duncan, can councils get Highcharts for free? If so, is it complicated to do?

If it's paid for/ complicated then we ought to provide another option. Are there any other options to try?

Thanks @dedavidson and @markconroy for sticking with this

**Comment by willguv** [comment]
@dedavidson could you post screenshots for both Highcharts and Chartjs please?

**Comment by dedavidson** [comment]
I have sent an enquiry to Highcarts.

**Comment by markconroy** [comment]
Did we have any response from HighCharts yet?

If not, I’m starting to think we presume our councils are all okay under the non-profit banner and we use HighCharts.

If it's deemed at a later date that councils do not fall under the non-profit banner, we can look at an alternative then. But let's try to not let this hold us up getting to beta/stable asap.

**Comment by willguv** [comment]
Do councils need a licence key or anything else to make Highcharts work?

Has anyone contacted Highcharts? Happy to message them today

**Comment by markconroy** [comment]
Duncan has contacted them, we haven't had a reply from them yet.

**Comment by finnlewis** [comment]
Might we include both and have it as a configuration option to use one or the other with appropriate licencing notes?

**Comment by dedavidson** [comment]
I think we'd have to create a sub-module for each given the changes that are required for each one.

**Comment by markconroy** [comment]
@willguv I've added some content and enabled the ChartJS implementation. By default it does not have colours. I'm guessing we could add them but from my reading this will take a bit of work (I'm not sure exactly how much, given that we want a custom colour set based on certain conditions).

Screenshot 2024-06-18 at 15 27 43

===
Thanks to [Big Blue Door](https://www.bigbluedoor.net/) for sponsoring my time to work on this.

**Comment by dedavidson** [comment]
I have code changes to add colours but as per my comment in https://github.com/localgovdrupal/localgov_elections_reporting/pull/59#issuecomment-2165018486 the other features are lost or more involved to add.

**Comment by willguv** [comment]
@dedavidson could you share your changes with @markconroy or commit them? I think this is passable with colors, but not without. Thanks.

The best solution is sticking with Highcharts - if we can get permission. If not, then I think it's Chartjs with colors.

**Comment by dedavidson** [comment]
@markconroy can you review the recent changes please

**Comment by finnlewis** [comment]
Closing this in favour of https://github.com/localgovdrupal/localgov_elections/pull/32

**Pull request closed without merging**
